### ISSUE TITLE
project name issue

### ISSUE THREAD

**Issue by abdullahknz** [ismkdc/CoronaVirusApi#1]
I get an error when compiling the project "There was an error 47: Wrong project name: It must be China Virus"

Please fix this issue.

Best regards.
-Donald J. Trump

**Comment by berkozturk97** [comment]
Thanks for error reporting Mr. Kanza. We will fix the issue as soon as possible.

-Arabian Software Development Consultancy

**Comment by abdullahknz** [comment]
> Thanks for error reporting Mr. Kanza. We will fix the issue as soon as possible.
> 
> -Arabian Software Development Consultancy

**Comment by ismkdc** [comment]
We will solve the problem with @yalcincakir
